server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT
    username: reader
    password: 123456
    druid:
      initial-size: 5 #connection pool size
      min-idle: 10 #min idle
      max-active: 20 #max idle
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #exclusion
      stat-view-servlet: #view eruser name and password
        login-username: druid
        login-password: druid
  redis:
    host: localhost #Redis server address
    database: 0 #Redis database index
    port: 6379 #Redis server connection port
    password: #Redis server connection password
    timeout: 300ms #Connection time out

logging:
  file:
    path: /var/logs
  level:
    root: info
    com.shawn.mall: info

logstash:
  host: logstash
