server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT
    username: root
    password: root
    druid:
      initial-size: 5 #connection pool size
      min-idle: 10 #min idle
      max-active: 20 #max idle
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #exclusion
      stat-view-servlet: #view eruser name and password
        login-username: druid
        login-password: druid
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mall-port
  redis:
    host: localhost #Redis server address
    database: 0 #Redis database index
    port: 6379 #Redis server connection port
    password: #Redis server connection password
    timeout: 300ms #Connection time out
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall

logging:
  level:
    root: info
    com.shawn.mall: debug

logstash:
  host: localhost